### ISSUE TITLE
Feature Request: add seekTo() method

### ISSUE THREAD

**Issue by bradmartin** [bradmartin/nativescript-audio#12]

**Comment by ChrisFlannagan** [comment]
If you need a hand on the iOS side of this I believe I can get that done for you.

**Comment by bradmartin** [comment]
For sure, thanks @ChrisFlannagan. If you get the iOS added in, I can handle the android no problem.

**Comment by bradmartin** [comment]
Closed via https://github.com/bradmartin/nativescript-audio/pull/17
