### ISSUE TITLE
Segmentation fault after DISPOSE

### ISSUE THREAD

**Issue by guru1966** [bradmartin/nativescript-audio#18]
Hello !
I get  Service exited due to Segmentation fault: 11
After playing audio files in mp3, m4a. Anyone know how to resolve this or debug it?

**Comment by bradmartin** [comment]
I've seen some segfault issues with iOS also. I'm not entirely certain about iOS issues. @NathanWalker you seen any segfault issues, I've reproduced with someone else's app and the code looks totally fine so I ran out of ideas.

**Comment by NathanWalker** [comment]
I'll see what I can figure out here over weekend.

**Comment by NathanWalker** [comment]
The PR above is several ts resolutions primarily.
@guru1966 I have tried to repro your issue but was unable to.
Audio track play to completion and then `dispose` is called when track completes in the demo and it works well.

If there are more specifics steps you could provide and/or provide some of the code you are using may help.

Also, what `tns-core-modules` and `tns` cli version are you using?

**Comment by NathanWalker** [comment]
@guru1966 I also went ahead and publish `2.1.2` which mainly just incorporates some ts improvements, but go ahead and pull that version and give it a shot.

**Comment by onury** [comment]
any news on this? I have the same issue.
I have tns version (next) 2.5.0-2016-12-23-7505 installed.

**Comment by bradmartin** [comment]
Can you provide a sample project to test? I've never ran into this myself

**Comment by onury** [comment]
What I do is essentially like the demo or source.

```js
    play(filePath:string, local:boolean = true):Promise<any> {
        let $this = this;
        let playerOptions:AudioPlayerOptions = {
            audioFile: filePath,
            loop: false,
            completeCallback() {
                console.log("Audio file complete");
                if (!playerOptions.loop) {
                    $this.player.dispose().then(() => {
                        $this.state = "stopped";
                    });
                }
            },
            errorCallback(error) {
                console.log("Error occurred during playback.");
                $this.state = "stopped";;
            },
            infoCallback(info) {
                console.log(JSON.stringify(info));
            }
        };

        if (local) {
            return this.player
                .playFromFile(playerOptions)
                .then(() => {
                    this.state = "playing";
                })
                .catch(err => {
                    console.log(err);
                    this.state = "stopped";
                });
        }
        // remote
        return this.player
            .playFromUrl(playerOptions)
            .then(() => {
                this.state = "playing";
            })
            .catch(err => {
                console.log(err);
                this.state = "stopped";
            });
    }
```

I bind this method to a tap event of a button. After tapping 2-3 times, it will throw segmentation error. (Note that whether I `.dispose()` or not, it throws).

I ended up using nativescript-sound module for now.

**Comment by jlooper** [comment]
Yeah, I'm going to chime in here, after trying to sort through proper disposal of my sound files when they are done playing, I sometimes experience app crashes with that seg fault. I just feel, with these input stream logs constantly running even after you dispose, that there's a memory leak. 

```
[aqme] 255: AQDefaultDevice (1): skipping input stream 0 0 0x0
[aqme] 255: AQDefaultDevice (173): skipping input stream 0 0 0x0
[aqme] 255: AQDefaultDevice (173): skipping input stream 0 0 0x0
CONSOLE LOG file:///app/app/frameworks/practicebuddy/components/teacher-student-home/teacher-student-home.component.ts:94:24: DISPOSED
[aqme] 255: AQDefaultDevice (173): skipping input stream 0 0 0x0
Jan 15 18:08:56 --- last message repeated 7 times ---
Jan 15 18:08:56 LOOPERMAC com.apple.CoreSimulator.SimDevice.1552CC18-C70B-4209-9F17-D04A886CD04C.launchd_sim[75110] (UIKitApplication:com.ladeezfirstmedia.practicebuddy[0x1fc8][43326]): Service exited due to Segmentation fault: 11
Jan 15 18:08:56 LOOPERMAC backboardd[75128]: [Common] Unable to get short BSD proc info for 43326: No such process
Jan 15 18:08:56 LOOPERMAC SpringBoard[75127]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
```

**Comment by NathanWalker** [comment]
Thanks for the reports here - will try to investigate this week.

**Comment by NathanWalker** [comment]
@jlooper could you provide a few more additional steps regarding your setup and how it could be replicated in the demo? I assume you tried it with the demo? That will help solve this for sure.

**Comment by jlooper** [comment]
hi, @NathanWalker - thank you! I am hitting this with PracticeBuddy. http://www.github.com/jlooper/practicebuddy-web-mobile. The thing I'm trying to do is have a bunch of buttons available on a card view for teachers to playback the minutes of practice time that their students are recording. 

The issue occurs sporadically, I'm pretty sure I saw it on PocketRave, too, where people can play remote tracks from Spotify. 

Here's the code in question (could stand some tidyup): https://github.com/jlooper/practicebuddy-web-mobile/blob/master/src/client/app/frameworks/practicebuddy/components/teacher-student-home/teacher-student-home.component.ts

**Comment by Juneil** [comment]
Hi, 

Just to say I have the same issue...
`(UIKitApplication:xx.yyyyy.myapp[0x2b6][81619]): Service exited due to Segmentation fault: 11`
It play well once and then it crash... Any news about this issue ? Thanks

The implementation is really simple : 
```
play(url: string) {
        this.player = new TNSPlayer();
        const options: AudioPlayerOptions = {
            audioFile: url,
            loop: false,
            completeCallback: () => {
                this.player.dispose()
                    .then(() => this.status$.next(AudioService.COMPLETE))
                    .catch((err) => console.error(err));
            },
            errorCallback: () => {
                this.status$.next(AudioService.COMPLETE);
            }
        };
        this.status$.next(AudioService.PLAYING);
        return Observable.fromPromise(this.player.playFromUrl(options));
    }
```

**Comment by ludwiktrammer** [comment]
I'm also experiencing the issue. Was anyone able to find an effective workaround?

**Comment by onury** [comment]
@jlooper [see this](http://stackoverflow.com/a/40501479/112731) for that stream log.

**Comment by bradmartin** [comment]
I think we have improved the plugin itself to avoid any issues. If anyone continues experiencing any issues please open a new issue on the repo and provide all of your code that is related to the audio plugin. As a note do not create new instances of a player without disposing a current player. Or just reuse a player instance you already have for playing audio.
