### ISSUE TITLE
NSURLSession.sharedSession not a function

### ISSUE THREAD

**Issue by smakinson** [bradmartin/nativescript-audio#25]
On ios I am seeing NSURLSession.sharedSession not a function when calling playFromUrl(options)

**Comment by bradmartin** [comment]
I'm no iOS expert but my guess is this is one of those methods to properties breaking changes Apple introduced. If so, easy fix. 
Ping @NathanWalker to confirm, I'll fix if that's correct 👍

**Comment by smakinson** [comment]
Thanks Brad! 

I came across this:

http://mrgott.com/swift-programing/30-work-with-rest-api-in-swift-3-and-xcode-8-using-urlsession-and-jsonserialization

looks like it confirms the issue. It looks like there is a shared property on the new stuff:

https://developer.apple.com/reference/foundation/urlsession

I also found a post that looks like there is a util that may be of use:

http://fluentreports.com/blog/?p=401

What do you think?

**Comment by bradmartin** [comment]
NativeScript has a utility method with 2.3 that handles the breaking change
from Apple. I'll add it and get the update published.

**Comment by bradmartin** [comment]
https://www.npmjs.com/package/nativescript-audio 2.1.3 published - if all good please close the issue.

**Comment by smakinson** [comment]
It looks like it gets past that point now and I see errors starting with line 54 in the generated js. 

I'm seeing null is not an object, it seems player is null.

**Comment by bradmartin** [comment]
It's possible I screwed up the usage of the utility :) not much of an iOS
guy so just shooting in the dark.

**Comment by NathanWalker** [comment]
This appears to be fixed in latest.
