### ISSUE TITLE
OSStatus error 2003334207

### ISSUE THREAD

**Issue by tiste** [bradmartin/nativescript-audio#26]
Hey,

I had issue to play sound on iOS so I went through running your demo, and found the same errors:

`CONSOLE LOG file:///app/main-view-model.js:132:24: NSErrorWrapper: The operation couldn’t be completed. (OSStatus error 2003334207.)`.

Btw, this bit of the demo needs to be updated: from `fs.knownFolders.currentApp().getFolder("audio")` to `fs.knownFolders.documents().getFolder("audio")`.

I'm unable to play sounds, neither from remote or local...

**Comment by Universi** [comment]
Hi,
@tiste, I get the same error.
Have you fixed it?

**Comment by tiste** [comment]
@Universi no, sorry... my project is in wip

**Comment by Universi** [comment]
@tiste Anyway, thank you for your answer ;)

**Comment by bradmartin** [comment]
I'm going to look into this soon. Will report with findings.

**Comment by Universi** [comment]
Hi @bradmartin,
I must specify that it works perfectly in iOS simulator with `knownFolders.documents()` ,  but not on the device.

**Comment by bradmartin** [comment]
Ah then I won't be much help there. Don't own iOS devices :)

**Comment by Universi** [comment]
New tests :
I don't have the `OSStatus error 2003334207` anymore, when testing on the device (using `documents() `instead of `currentApp()`.
The recording is OK, since `File.exists(recordedFile.path)` returns `true`.
However, the player gives me "IS PLAYING" (see my code below) without producing any sound.
The volume is ON (10/10) and permissions are granted in Info.plist file.
```
this.player.playFromFile(playerOptions).then(() => {
      this.set("isPlaying", true);
      console.log("IS PLAYING");
    }, (err) => {
      console.log(err);
      this.set("isPlaying", false);
    });
```

@NathanWalker @bradmartin Would you have an idea ?

**Comment by psobolewski** [comment]
Hi,
@bradmartin have you resolve this problemy? I try to use TNSPlayer and it still appears. 
`CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): NSErrorWrapper: The operation couldn’t be completed. (OSStatus error 2003334207.)`

Maybe I am doing sth wrong. Below I paste my simple code:

```
import {Router} from "@angular/router";
import {Page} from "ui/page";
import {Component, ElementRef, OnInit, ViewChild} from "@angular/core";
import {Shout} from "../../shared/shout/shout";
import {ShoutService} from "../../shared/shout/shout.service";
import { TNSPlayer } from 'nativescript-audio';
import {knownFolders} from "tns-core-modules/file-system";

import * as fs from "tns-core-modules/file-system";

@Component({
    selector: "my-app",
    providers: [ShoutService],
    templateUrl: "pages/shout/shout.html",
    styleUrls: ["pages/shout/shout-common.css", "pages/shout/shout.css"]

})
export class NewShoutComponent implements OnInit {
    private _player: TNSPlayer;
    @ViewChild("container") container: ElementRef;

    constructor(private router: Router, private page: Page, private shoutService: ShoutService) {
        var documents = fs.knownFolders.documents();
        var filePath = fs.path.join(documents.path, "audio/song.mp3");
        var f = documents.getFile(filePath).readSync()


        this._player = new TNSPlayer();
        this._player.initFromFile({
            audioFile: filePath,
            loop: false,
        }).then(() => {      });
    }
}
```
