### ISSUE TITLE
Can't run demo on emulator and device

### ISSUE THREAD

**Issue by kr1stjans** [bradmartin/nativescript-audio#27]
I am trying to run demo project on emulator and device and it gives me the following error:

nativescriptaudiomaster[10539]: undefined: JS ERROR Error: Could not find module './'. Computed path '/Users/username/Library/Developer/CoreSimulator/Devices/9787AD04-4D86-4193-A304-D49D5B45CC17/data/Containers/Bundle/Application/41F49A6B-B7AE-49A4-9615-04603C1E1E51/nativescriptaudiomaster.app/app'.
com.apple.CoreSimulator.SimDevice.9787AD04-4D86-4193-A304-D49D5B45CC17.launchd_sim[10279] (UIKitApplication:username[0x8487][10539]): Service exited due to Segmentation fault: 11

I haven't changed anything. Pure project doesn't work on device or emulator. Any suggestions? Does it work for others? I am on XCode 8.1.

I tried to do this, because when I try to use the library in my project, no sound is played and no errors are given. Anyone else experienced this? This is the code that I use:
```
this.player = new TNSPlayer();
this.playAudio('~/faded.mp3', 'localFile');
/* this.playAudio('https://dl.dropboxusercontent.com/u/50681696/content/Alan%20Walker%20-%20Faded.mp3', 'remoteFile'); */

public playAudio(filepath: string, fileType: string) {
        try {
            var playerOptions: AudioPlayerOptions = {
                audioFile: filepath,
                loop: true,
                completeCallback: () => {
                    this.player.dispose().then(() => {
                        console.log('DISPOSED');
                    }, (err) => {
                        console.log('ERROR disposePlayer: ' + err);
                    });
                },

                errorCallback: (err) => {
                    console.log(err);
                },

                infoCallback: (info) => {
                    console.log("what: " + info);
                }
            };

            if (fileType === 'localFile') {
                this.player.playFromFile(playerOptions).then(() => {
                }, (err) => {
                    console.log(err);
                });
            } else if (fileType === 'remoteFile') {
                this.player.playFromUrl(playerOptions).then(() => {
                }, (err) => {
                    console.log(err);
                });
            }
        } catch (ex) {
            console.log(ex);
        }
}
```

**Comment by bradmartin** [comment]
Did you solve the issue?

**Comment by kr1stjans** [comment]
Yep, nativescript-audio path wasn't defined in package.json. You can delete the issue. I could only close it.

**Comment by bradmartin** [comment]
Ok. No worries. Thanks for confirming :)
