### ISSUE TITLE
Audio randomly stops playing on android device

### ISSUE THREAD

**Issue by rezonjov** [bradmartin/nativescript-audio#31]
I made an app that make a sound whenever a task is completed. And sometimes, the audio doesn't play. But then it will work just fine for most of the time.  

Here's the error status: {"mp":{},"what":100,"extra":0}

Does anyone know what happen?

**Comment by bradmartin** [comment]
If you're playing a short sound clip (less than 5 seconds) I'd try out the
nativescript-sound plugin and see if it works better. This plugin might be
a bit much to just play a sound clip numerous times like you might be
doing. Hope that helps.

**Comment by rezonjov** [comment]
@bradmartin  Thanks for the reply. The app indeed plays a sound clip numerous time with an interval of 4-7 seconds. I'll check out nativescript-sound plugin! I guess we can close the issue for now
