### ISSUE TITLE
Set Volume on a player

### ISSUE THREAD

**Issue by vmechele** [bradmartin/nativescript-audio#35]
Hi guys,

How could I est the volume on a player. 

I am using 6 players on my app which should be able to play at different volumes. 
I couldn't find a module that sets the volume (like on EZPlayer).

How could I add this to my app?,

Thanks!

**Comment by bradmartin** [comment]
Adding this on Android wouldn't be difficult in fact, added to the video player here
https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.android.ts#L431
Not sure without digging on the iOS specifics but we did the same for iOS on video so assuming it's the same classes for audio/video on iOS it should be relatively easy to add in a public method for this and add to the options passed into the constructor of the audio player.

**Comment by NathanWalker** [comment]
@vmechele `volume` is now available as a getter/setter with `3.2.0` published now 👍
