### ISSUE TITLE
Getting this error on android

### ISSUE THREAD

**Issue by manishmlv50** [bradmartin/nativescript-audio#37]
Error: java.lang.RuntimeException: setAudioSource failed.
JS:     android.media.MediaRecorder.setAudioSource(Native Method)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
JS:     android.view.View.performClick(View.java:5207)
JS:     android.view.View$PerformClick.run(View.java:21177)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5441)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by bradmartin** [comment]
Please provide the code you are executing when this error is thrown.
