### ISSUE TITLE
Android Crashes

### ISSUE THREAD

**Issue by dylanryan** [bradmartin/nativescript-audio#4]
2 semi-related issues.

On android, playFromFile requires all the callbacks to be present, because it unconditionally sets the callbacks (unlike playFromUrl which only sets them if they are present). These should be optional (since the docs imply they are)

Second, the onErrorListener and onInfoListener are supposed to take functions that return boolean (see http://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener.html and http://developer.android.com/reference/android/media/MediaPlayer.OnInfoListener.html ), and it crashes trying to get the boolean value of the return value. This applies to both playFromFile and playFromUrl.

**Comment by bradmartin** [comment]
Good catch on the methods and I agree, they should be optional :+1: I don't have time right now to make the changes, if you do, submit a PR and I'll merge and update the plugin. Thanks :)

**Comment by dylanryan** [comment]
Will do. I also am going to do a quick implementation of completion and error callbacks on iOS. I don't see any equivalent of the info callback in the docs, so I won't do that on iOS.

**Comment by bradmartin** [comment]
Merged #5, going to update and publish. Thanks @dylanryan good work :sunglasses:
