### ISSUE TITLE
How to add Seekbar?

### ISSUE THREAD

**Issue by iridiumsoft** [bradmartin/nativescript-audio#40]
Hi, I',m using this plugin for my application and its working really good, but i want to make a seek bar where users can change audio track position. Unfortunately i could no see this option in provided document. Is there any way?
Quick reply will be really appreciated.
Thanks

**Comment by bradmartin** [comment]
You can add a slider to your app and use the audio players getAudioTrackDuration() method to determine the max of the slider and then you could use the sliders change even and when the value changes you could use the players `seekTo()` method. Those methods are on the readme so I might have misspelled them (on phone right now)

**Comment by iridiumsoft** [comment]
Thanks for quick reply, I was gonna do the same thing but i can get only track duration not the current position, without that its not possible

**Comment by bradmartin** [comment]
Gotcha. That can be added and should be. If you wanted to make an attempt
at a PR you could look at the source code for the video player plugin and
see how to do it on Android and iOS and expose that functionality here. I'd
be happy to answer questions along the way. If you don't want to, it will
be a little while before I have time to do it myself.

**Comment by bradmartin** [comment]
Here is the android source to see how easy it would be to add https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.android.ts#L424 - I just don't have time to add and test both platforms after adding to make sure all works great 😄

**Comment by bradmartin** [comment]
I'm going to log a new issue with the feature request for `getCurrentTrackPosition` and close this issue. Thanks for bringing this up.

**Comment by iridiumsoft** [comment]
Hi Thanks @bradmartin for the suggestions, I will surely look onto that :)

**Comment by NathanWalker** [comment]
@iridiumsoft currenTime is a getter on the player, works perfect on iOS and android: https://github.com/bradmartin/nativescript-audio/issues/41#issuecomment-287778426
