### ISSUE TITLE
Feature Request: Get audio tracks current position in time

### ISSUE THREAD

**Issue by bradmartin** [bradmartin/nativescript-audio#41]
Ref here #40 

The source is on the video player plugin for Android. Have not checked iOS for the correct usage with audio playback.

**Comment by NathanWalker** [comment]
This is already available. currentTime on the player:
https://github.com/bradmartin/nativescript-audio/blob/master/src/android/player.ts#L251
Works great for iOS and Android.

**Comment by bradmartin** [comment]
Can't believe I missed that 👍

**Comment by NathanWalker** [comment]
Thanks yeah I thought it was on readme 👍

**Comment by iridiumsoft** [comment]
Thank you guys, It works for me :)
