### ISSUE TITLE
Potential bug / issue: setAudioSource failed.

### ISSUE THREAD

**Issue by Taremeh** [bradmartin/nativescript-audio#42]
I installed the plugin and copied the demo-code.
Unfortunately I got an error every time I wanted to record audio:

```
Error: java.lang.RuntimeException: setAudioSource failed.
JS:     android.media.MediaRecorder.setAudioSource(Native Method)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1047)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1028)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1018)
JS:     com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
JS:     android.view.View.performClick(View.java:5226)
JS:     android.view.View$PerformClick.run(View.java:21266)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:168)
JS:     android.app.ActivityThread.main(ActivityThread.java:5845)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

No improvements after I added the permission to the AndroidManifest.xml:
`<uses-permission android:name="android.permission.RECORD_AUDIO" />`

Then after changing the targetSdkVersion from "`__APILEVEL__`" to "22", it worked:

```
<uses-sdk
	android:minSdkVersion="17"
	android:targetSdkVersion="22"/>
```

If this isn't a bug, it could be helpful to mention it in the README?

However I'm glad, that it works now 👍

**Comment by bradmartin** [comment]
If changing the target SDK to 22 worked then I think it's permissions. So
definitely need to add something to the readme about using the permissions
plugin or adding it to this plugin to handle asking for permissions on 23+

**Comment by 1392324000** [comment]
I copied Demo codes in my project,and changed the targetSdkVersion from "__APILEVEL__" to "22",it gave me the same error,"java.lang.RuntimeException: setAudioSource failed..."  @bradmartin @Taremeh

**Comment by bradmartin** [comment]
Make sure to uninstall any old .apks from emulator/device, make the change to manifest, rebuild and then run. Should take care of it @1392324000

**Comment by 1392324000** [comment]
I tried,it dialog the same err again...
Another question: Why pakage the AudioDemo module in ModelView file,bu not in main js file?
 :-) @bradmartin

**Comment by bradmartin** [comment]
I might be misunderstanding what you mean, but if you mean why is the demo using the viewmodel and not just using the main.ts/js file. Then it was just preference 😄 - no good reason. If you mean something else by that question let me know and I'll try to answer 👍

**Comment by 1392324000** [comment]
You did got my meaning.In fact,I meet three reuslts.
The first,I cloned your demo ,install on my device ,run,...every function is ok,pretty good!
The 2nd,I copied your demo code in my project,fix the "__APILEVEL__" to "22" in the AndroidManifest.xml file,...It shows me error massage.
And the last,I tried to code the AudioDemo module's functions in main js file ,export functions to View...nothing happend.

Below is some code in my main js file:
`var frames = require("ui/frame");
var audioModel = require("nativescript-audio");

var page, kind, kindInfo, project, recordering;
var fs = require("file-system");
var platform = require("platform");
var player = new audioModel.TNSPlayer();
var recorder = new audioModel.TNSRecorder();
var audioFolder = fs.knownFolders.currentApp().getFolder("audio");
exports.onLoaded = function (args) {
    page = args.object;

}

exports.goback = function () {
    frames.topmost().goBack();
};


exports.recorder = function () {
    if (audioModel.TNSRecorder.CAN_RECORD()) {
        
        //alert(JSON.stringify(audioFolder));
        var androidFormat = void 0;
        var androidEncoder = void 0;
        if (platform.isAndroid) {
            androidFormat = 2;
            androidEncoder = 3;
        }
        var recordingPath = audioFolder.path + "/recording." + "m4a";
        //alert(recordingPath);
        var recorderOptions_1 = {
            filename: recordingPath,
            format: androidFormat,
            encoder: androidEncoder,
            metering: true,
            infoCallback: function (infoObject) {
                alert(JSON.stringify(infoObject));
            },
            errorCallback: function (errorObject) {
                alert(JSON.stringify(errorObject));
            }
        };
        recorder.start(recorderOptions_1);
    }
    else {
        alert("This device cannot record audio.");
    }
}
exports.stop = function () {
    recorder.stop().then(function () {
        alert("stop");
    })
}

exports.getFile = function (args) {
    try {        
        var recordedFile = audioFolder.getFile("recording." + "m4a");
        console.log(JSON.stringify(recordedFile));
        alert('recording exists: ' + fs.File.exists(recordedFile.path));
    }
    catch (ex) {
        alert(ex);
    }
};
exports.play = function () {
    
    var recordedFile = audioFolder.getFile("recording." + "m4a");
    var playerOptions = {
        audioFile: recordedFile,
        loop: false,
        completeCallback: function () {

        },
        errorCallback: function (errorObject) {

        },
        infoCallback: function (infoObject) {

        }
    };
    player.playFromFile(playerOptions).then(alert("play"));
}`

Thank you for your patience. :-)
@bradmartin

**Comment by mukuriaevans** [comment]
my also worked after adding the sdk minversion bad target version

**Comment by mukuriaevans** [comment]
mine also worked after adding the sdk minversion and target version. am just a newbie
thanks for the help
