### ISSUE TITLE
URL with Referer

### ISSUE THREAD

**Issue by yoannlal** [bradmartin/nativescript-audio#46]
Hi,

The URL that i'm calling need to be called with a referer.
Any idea how I can perform this with this plugin ?

Thanks !

**Comment by bradmartin** [comment]
Do you have some sample code of this on Android or iOS? I'm not sure what you are referring to :)

**Comment by yoannlal** [comment]
Well, sorry, I'm coming from the web, I wouldn't be sure.
It looks like in iOS, HTTP headers can be changed like this
`[request setHTTPMethod:@"GET"];
  [request setValue:@"https://whatever.com" forHTTPHeaderField: @"Referer"];`

The idea behind is that the URL I call (https://music.company.com/....d.mp3) will refuse me the access if I don't provide a referer in the HTTP request headers and make the app crash.

Not sure if there is a way to tackle this :)

**Comment by bradmartin** [comment]
Circling back to this, did you figure it out? You need an HTTP header, I was confused by referer 😄 . We would need to see if the iOS media player has a built in way to add headers for remote files playback or we can see about adding some work around to it. When you request that mp3 does it return a response or is that specifically to playback the `.mp3` file at that url?
