### ISSUE TITLE
Can't play my recorded file into web browser

### ISSUE THREAD

**Issue by demym** [bradmartin/nativescript-audio#54]
Hi, i finally succeeded to record an mp3 file with the plugin in android.

I used outputformat 2 (that i think should be MPEG_4) and audio encoder 1. 
I have the need to post this recorded file to the web, so i encode it as Base64 and transfer it prepending data:audio/mp3;base64, to the encoded.

But that file, that correctly plays on my phone (which recorded it) does not play on the web (only on Safari, but not on chrome, mozilla, ecc...).

I previously did the same thing in another cordova app of mine, and using the media-capture plugin i could correctly listen to the phone recorded files onto the web (where i put them inside and HTML5 <audio> tag.

Can someone please help me ?

Thanks in advance

**Comment by bradmartin** [comment]
@demym - do you have a sample file you can upload here? Do you have an .mp3 to use on the web after you transfer it?
