### ISSUE TITLE
Feature Request: Add pause() method to recorder

### ISSUE THREAD

**Issue by gtnunes1956** [bradmartin/nativescript-audio#57]
It would be a useful enhancement for this plugin to have a 'pause()' feature available for the recorder, so as to allow pausing and resuming recording within the same configuration state. Incidentally, this  is a feature available natively on both Android and iOS environments.

**Comment by bradmartin** [comment]
Great idea. I don't have time for this right now but this is something fairly trivial to add for Android. Actually can't believe I overlooked it during the original implementation 😄 
@gtnunes1956 are you familiar with using the native android/ios APIs? If not and you'd like to try, I can help point you in the right direction to submit a PR for this functionality.

**Comment by gtnunes1956** [comment]
It will be a pleasure to do it, and share it with the community. I am new to PRs though, but I figure it can't be that complicated. I am very comfortable with Android, and their API has both "pause()" and "resume()" for the recorder. As for the iOS API, it has "pause()" and "record()" (the latter behaves as 'resume' if invoked on a paused recorder). My difficulty, though, is not having access to a mac, and thus not being able to actually test the iOS-target code (which, anyway, would be very straightforward and trivial). @bradmartin, your thoughts.

**Comment by bradmartin** [comment]
Awesome, great attitude to have 👍 - as for PRs, it's really simple. Fork this repo, then clone it on your machine, do your work, commit the changes to your fork and then on Github you'll be able to `Create a Pull Request` (it's a button on the forked repo home page, you'll see it) and that's it. Then I'll review and merge it to the main repo and publish the updates to npm and done 😄 

I have a mac but I'm not great with iOS but I can figure it out if you want to work on android and make a quick attempt at iOS based on the methods you've found on the correct classes we use and I'll test iOS and get it working (hopefully).

**Comment by gtnunes1956** [comment]
@bradmartin, I have completed the pull request. To verify the added feature on the Android platform, I make a quick adaptation to your demo code (https://bradmartin.net/2016/05/03/recording-audio-in-a-nativescript-app/), with two more buttons (pause/resume) and a play action (https://github.com/gtnunes1956/audio-recorder). The changes were minor (basically, copy-and-paste plus light editing of a few small fragments of the original code - my editor strips trailing blanks, so some extra 'modified' lines were reported - I apologize for that). The iOS side remains to be validated. Regards.
