### ISSUE TITLE
How to record

### ISSUE THREAD

**Issue by davidmontgom** [bradmartin/nativescript-audio#60]
Do you have a simple example of of to start and stop a recording?  Docs are totally not clear.  Yoju one example is for android.  What about iOS?  demo/app/main-view-model.ts

Thanks

**Comment by bradmartin** [comment]
Can provide some sample later but for now https://github.com/bradmartin/nativescript-audio/blob/master/README.md#api you should check if recording is possible on the device. Then use the recorder start stop methods. Late night right now :) ping me if you need a quick code sample. I'll paste something to help out :) thanks for checking out the plugin.
