### ISSUE TITLE
I can't play my recorded file just after using recorder, but only after restarting my app

### ISSUE THREAD

**Issue by Universi** [bradmartin/nativescript-audio#61]
Hi,

I can't play my recorded file just after using recorder.
If I play the recorded file before using TNSRecorder, it works perfectly.
But if I use TNSRecorder, I can't play the recorded file anymore, until I restart my app.

Can there be any (channel ?) conflict between AVAudioPlayer and AVAudioRecorder?

Thank you in advance for your help.

**Comment by bradmartin** [comment]
Demo app shows this working. If still an issue let me know.
