### ISSUE TITLE
Nativescript-audio and -videoplayer can't be controlled alongside each other

### ISSUE THREAD

**Issue by schnapzz** [bradmartin/nativescript-audio#64]
Hi

First of all thanks for some great plugins guys! have made the progress on my latest project much faster and much easier.
But.. I'm now in a situation where i'm in need of running separate audio tracks alongside a video being played.
Assumed i have set it up correctly (more on that further down the post), this is how i try to handle pause() and play() for both audio and video.

```
cycleVideoPlayer.on(gestures.GestureTypes.swipe, function(eventdata) {
    console.log("Swipe detected, with direction: " + eventdata.direction);
    if (!paused) {

        vm.audioPlayer.pause()
        .then((result) => {

          paused = true;
          const id = timer.setTimer(() => {
            vm.cycleVideoPlayerViewModel.pause(); //This doesnt work alongside audiopause.. why?
            console.log("cycleVideo should be paused");
          },500);

        }, (err) => {

          console.log("pause sound and video failed with error:\
                      " + err);
        });
        console.log("Paused");
      
    } else {
      
        vm.audioPlayer.resume()
        .then((result) => {

          paused = false;
          const id = timer.setTimer(() => {
            vm.cycleVideoPlayerViewModel.play();
            console.log("cycleVideo should be playing");
          }, 500);

        }, (err) => {

          console.log("resume sound and video failed with error:\
          " + err);
        });
        console.log("Resumed");          
    }
  });
```

I've made a post on stackoverflow which describes the situation in more detail. I still haven't solved the issue and hope you guys can help another dev out :)
Link to stackoverflow: [https://stackoverflow.com/questions/44927740/cant-make-nativescript-videoplayer-and-nativescript-audioplayer-work-alongside](url)

Hope to hear from you

// Mikkel

**Comment by schnapzz** [comment]
Figured I had to do this from the view-model.js instead of the page.js. This is not an issue, it can be closed. Sorry for the trouble :)

**Comment by bradmartin** [comment]
All good, glad you sorted it out 😄. I'd eventually have gotten back to you, just little free time right now.
