### ISSUE TITLE
Eliminate the "dependancy" on tns-core-modules

### ISSUE THREAD

**Issue by NathanaelA** [bradmartin/nativescript-audio#67]
Some versions of NPM will install dependencies in a node_modules of the **plugin**.  When you get TWO tns-core-modules in your project; the project can crash on Android with a really weird error message about having to use frame to navigate.  

IF you need to fix it to a version of the runtime use a "peerDependencies"

**Comment by bradmartin** [comment]
changed to peerdep for now
