### ISSUE TITLE
Issue with published package > 3.5.0

### ISSUE THREAD

**Issue by sean-perkins** [bradmartin/nativescript-audio#68]
Note to all, until this addressed. 

The package contents in versions greater than 3.5.0 are currently missing. 

Until you see this issue closed, install 3.5.0 directly:
```
npm install nativescript-audio@3.5.0 --save
```

To do list:
- Update dependencies
- Solve `tsc` fail error

**Comment by NathanWalker** [comment]
I'll take a look shortly @sean-Perkins thanks for heads up. Perhaps we can just add ya as collaborator.
