### ISSUE TITLE
. Processing node_modules failed. Error: cp: cannot create directory 'D:/xgm/demos /nativescript/nativescript-audio-master/demo/platforms/android/src/main/assets/a pp/tns_modules': No such file or directory

### ISSUE THREAD

**Issue by bright999** [bradmartin/nativescript-audio#77]
D:\xgm\demos\nativescript\nativescript-audio-master\demo>tns build android --com
pileSdk 25
Executing before-prepare hook from D:\xgm\demos\nativescript\nativescript-audio-
master\demo\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.5.3
Preparing project...
Processing node_modules failed. Error: cp: cannot create directory 'D:/xgm/demos
/nativescript/nativescript-audio-master/demo/platforms/android/src/main/assets/a
pp/tns_modules': No such file or directory
Sending exception report (press Ctrl+C to stop)....

in D:\xgm\demos\nativescript\nativescript-audio-master\demo
1.tns install
2.tns build android --compileSdk 25
the error is happen

I use the demo,no changed

tns info:
All NativeScript components versions information
──────────────┬──────────────────┐
│ Component           │ Current version │ Latest version │ Information         │
│ nativescript           │ 3.2.0                   │ 3.2.1                │ Update available │
│ tns-core-modules │ 3.2.0                   │ 3.2.0                │ Up to date           │
│ tns-android           │ 3.1.1                   │ 3.2.0                │ Update available │
│ tns-ios                   │                            │ 3.2.0               │ Not installed        │
└─────────────────              ─┴─────────────────┴──
![
![111](https://user-images.githubusercontent.com/4628237/31373995-bfd49840-adce-11e7-8e4e-d5da6e68e7b8.png)

**Comment by bradmartin** [comment]
Update your runtime to match core-modules, typically you want to keep those in sync. Nuke your project (node_modules, hooks, platforms). Add platform back and run once it's all been updated and your build should be fixed.
