### ISSUE TITLE
What is the best approach to replay from the beginning

### ISSUE THREAD

**Issue by xhe** [bradmartin/nativescript-audio#79]
I thought it should be easy, but tested some solutions, and not not working
when a sound is finished, how can I go back to beginning and let user play it again?

I used this logic:

```
this._player.seekTo(0);
this._player.pause();
this.btnTitle = "Start";
```

but when user click the button, this._player.start() is not playing sound at all.

Any suggestions? Thanks

**Comment by bradmartin** [comment]
Can you provide more code around those few lines. I think it would be helpful to see a full implementation that you are taking. Thanks.

**Comment by xhe** [comment]
This is what I was doing:

                    this._player.initFromUrl({
                        audioFile: this.item.enclosure_link,
                        loop: false,
                        completeCallback: this._trackComplete.bind(this),
                        errorCallback: this._trackError.bind(this),
                        infoCallback: this._infoCallback.bind(this)
                    }).then(() => {

this._player.getAudioTrackDuration().then((duration) => {
                            this._player.volume = 1;
                            // iOS: duration is in seconds
                            // Android: duration is in milliseconds
                            var duration_i: number = parseInt(duration);

                            if (this.platform == 'android') {
                                duration_i = duration_i / 1000;
                            }

                            this.totalLength = duration_i;
                            this.totalLength_s =
this._convertTS(duration_i);

                            this.loaded = true;
                            this.showPlayBtn = 'visible';
                            this.timerId = timer.setInterval(() => {
                                var currentTime: number =
Math.floor(this._player.currentTime);
                                if (this.platform == 'android') {
                                    currentTime = currentTime / 1000;
                                }
                                console.log(currentTime+' ---
'+this.totalLength);
                                if (currentTime < this.totalLength-1) {
                                    console.log('pos 1 ');
                                    this.currentTime = currentTime;
                                    this.currentTime_s =
this._convertTS(currentTime);
                                    this.progressValue = (this.currentTime
/ this.totalLength) * 100;
                                } else {
                                    console.log(' pos 2 ');
                                    //timer.clearInterval(this.timerId);
                                    // this._player.seekTo(0);
                                    // this._player.pause();
                                    this.btnTitle =
this.rssService.trans("Start", "开始");
                                }
                            }, 1000);

                            this.audioInitiated = true;

                        });
                    });

togglePlay() {
            if (this._player.isAudioPlaying()) {
                this._player.pause();
                this.btnTitle = this.rssService.trans("Resume", "重新开始");
            } else {
                this._player.play();
                this.btnTitle = this.rssService.trans("Pause", "暂停");
            }
        }


But once the button shows "Start" from "Pause", and I click the button
again, nothing happened.

I don't know if there are any logic error for the action I applied after
the sound is finished playing.

Thanks
