### ISSUE TITLE
resume method after pause audio from url

### ISSUE THREAD

**Issue by cinder92** [bradmartin/nativescript-audio#8]
Thanks for your nice plugin, i'm playing a streaming from url, from here everything is ok, but when i tap pause method and then play, it takes time to resume streaming, like 3 or 4 seconds.

Is there any change that you can add resume method from URL?

Thanks! #

**Comment by bradmartin** [comment]
I'll have to look into what's possible, from memory I'm not sure what's available 'out of the box' from android and iOS in regards to handling that.

**Comment by bradmartin** [comment]
`resume()` added to the Player.
