### ISSUE TITLE
 setDataSourceFD failed.: status=0x80000000

### ISSUE THREAD

**Issue by alexrait** [bradmartin/nativescript-audio#81]
This is the error I get when using playFromFile on Android.
Tried various mp3 files including the one in the demo here.

**Comment by bradmartin** [comment]
The demo appears to be working fine with no errors thrown. Can you try the demo by `clone`ing and then cd into the `src` directory and run `npm run demo.android` this should kick off the demo after a full build. Let me know what happens. Thanks.
