### ISSUE TITLE
Multiple files   - code structure ?

### ISSUE THREAD

**Issue by RoyiNamir** [bradmartin/nativescript-audio#85]
Looking at your code sample in the git , what if I have 5 buttons  and I want that each one will play a different sound ? 

Should I create 5 instances of `TNSPlayer`?

Can u plz give an example ?

**Comment by bradmartin** [comment]
I've never tried that. Are you playing large audio files or small sound clips? If they're short audio clips you might have a good option to use the `nativescript-sound` plugin. You could always try to initialize the `TNSPlayer` of this plugin and then reuse that one instance to play all your audio files but I don't think the native APIs allow you to play multiple files at once with one media player. Here is the android API https://developer.android.com/reference/android/media/MediaPlayer.html for reference and from what I recall one media player can play one audio file at a time so if you are wanting to tap multiple buttons and play the sound you'd need 5 instances of the player.

**Comment by RoyiNamir** [comment]
@bradmartin I'm not talking about playing at once. Say I have 5 buttons and I want each to play a different sound. ( a game for a kid  - for example)

**Comment by RoyiNamir** [comment]
Thank you for replying.
