### ISSUE TITLE
Won't play files in RAW folder ?

### ISSUE THREAD

**Issue by RoyiNamir** [bradmartin/nativescript-audio#86]
This is my structure : 

![image](https://user-images.githubusercontent.com/2842123/33322493-352cb628-d452-11e7-9bdf-2d507eca329e.png)

it  shows an error whic apparently is file not found : 

![image](https://user-images.githubusercontent.com/2842123/33322567-6bc9225c-d452-11e7-9cf9-c8606e72d641.png)

However - if the folder is outside the  project at the root :   - it does work : 

![image](https://user-images.githubusercontent.com/2842123/33322632-a2cf820a-d452-11e7-94cf-797e9a8c24cd.png)

**Question:**

How can I access appropriately to the `raw`  resource folder ( and not some outside folder) ?

**Comment by bradmartin** [comment]
I've never tried this myself. You might have to use `android.R.raw` to get the path using the NS `file-system` module and convert it to something the plugin currently handles. If that doesn't work, I'd certainly accept a PR adding the functionality of picking up the `raw` resource path and using it.
Here: https://github.com/bradmartin/nativescript-audio/blob/master/src/android/player.ts#L34 is a good place to get started on the source.

**Comment by RoyiNamir** [comment]
@bradmartin I'm just curious - so where is the *right* place to put *generated* files ? Is it in the `fs.knownFolders.documents()` ?

**Comment by bradmartin** [comment]
what do you mean by `generated` files?

**Comment by RoyiNamir** [comment]
@bradmartin  Say a person record a voice via the app and the app needs to save it. where would you save it ? in `fs.knownFolders.documents()` ?? 

BTW thank you for your patience and knowledge. 👍

**Comment by bradmartin** [comment]
Here https://github.com/bradmartin/nativescript-audio/blob/master/demo/app/main-view-model.ts#L86 is how I originally stored the recorded files in the demo app.
