### ISSUE TITLE
Error and Info callbacks

### ISSUE THREAD

**Issue by slavaGanzin** [bradmartin/nativescript-audio#9]
Why https://github.com/bradmartin/nativescript-audio/blob/master/src/android/player.ts#L104 error/info events do not provide `mp, what, extra` into callbacks?

**Comment by bradmartin** [comment]
To be honest, probably just overlooked it. If you want to submit a PR with the necessary fixes that would be great.

**Comment by bradmartin** [comment]
Fixed with 3.0.0 release - returning objects containing any native values passed in the event listeners.
